### ISSUE TITLE
Export orders to CSV

### ISSUE THREAD

**Issue by danielkucera** [arturo182/lectronizer#18]
Hi,
thank you for the project.
I am trying to solve shipping with Slovak Post. There are 4 options:
- xls (:vomiting_face: ) sheet with destinations, template: https://www.posta.sk/subory/38647/sablony-xls-pre-podaj.zip
- xml (:nauseated_face: ) [EPHtemplate.zip](https://github.com/arturo182/lectronizer/files/10075818/EPHtemplate.zip)
- soap api (:vomiting_face: ) https://www.posta.sk/subory/39028/manual-pre-implementaciu-web-eph-api.pdf
- rest api (returning 401) https://mojezasielky.posta.sk/pomoc/webeph-api/

Everything in Slovak (of course :man_facepalming: )

The path of least resistance I see now would be the possibility to mark orders in the application and export as csv or json.
From there I would do some python crunching and generate xml.

Would it be possible to provide the export functionality?
Or provide a templating system to generate any form of text output from selected orders?

**Comment by arturo182** [comment]
Hi Daniel,

Yes, I am planning to add an export to csv functionality where you can define which columns and in what order you want to be exported. However, I am a bit limited on time at the moment so not sure when this will happen. I'll rename this issue and keep it open to track the export functionality :)

**Comment by danielkucera** [comment]
Thank you, I ended up writing my own set of scripts, it was not that hard in the end :)
https://github.com/danielkucera/lectronzshipper

**Comment by arturo182** [comment]
I can't see the repo, possibly private?

**Comment by danielkucera** [comment]
I published something accidentally, now it is public.

**Comment by arturo182** [comment]
I have now added a Bulk Exporter tool.
It's accessible from the Tools menu and via the F8 shortcut.
The Exporter takes the list of orders that are visible in the main window, including filters and search, and generates csv from them.
The user can select the columns they want to export and in what order.
The columns and their order can be saved as presets so the user can have multiple presets for various export scenarios.
The user can also change the csv separator in the Settings.
There might be bugs, lol

Preview:
![image](https://user-images.githubusercontent.com/249082/209454745-0a68ecd9-44b1-4e45-bd61-daa3e73647f8.png)
