### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: charts

### ISSUE THREAD

**Issue by nshiell** [arturo182/lectronizer#20]
Trying to build
When I run:
```
qmake .
```
I see:
```
Info: creating stash file /home/nicholas/Documents/playground/lectronizer/.qmake.stash
Project ERROR: Unknown module(s) in QT: charts
```

System is:
Kubuntu Linux 22.04
Qt Version 5.15.3

**Comment by arturo182** [comment]
You need the `libqt5charts5-dev` package installed.

You can see the list of packages needed on Ubuntu here: https://github.com/arturo182/lectronizer/blob/main/.github/workflows/build.yml#L45

**Comment by nshiell** [comment]
Seems to build ok if I run:
```sudo apt install libqt5charts5-dev```
before using qmake

**Comment by arturo182** [comment]
Great :)
